select DATEADD(YEAR, 10, GETDATE())

select DATEADD(MONTH, 10, GETDATE())

select DATEADD(DAY, 10, GETDATE())

select DATEADD(WEEK, 10, GETDATE())

select DATEADD(HOUR, 10, GETDATE())

select DATEADD(MINUTE, 10, GETDATE())